name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # Chạy sạch sẽ, chạy test và đóng gói jar
        run: mvn clean package

      - name: Upload Build Artifact
        # Lưu file .jar để kiểm tra sau khi build thành công
        uses: actions/upload-artifact@v4
        with:
          name: math-utils-jar
          path: target/*.jar